/*
 * File: resources/js/faculty/ai/prompts.js
 * Description: Central place to manage prompt snippets per syllabus partial.
 * API:
 *   - SVPrompts.get(key): returns a prompt string for the partial key or default.
 *   - SVPrompts.set(key, prompt): override/add a prompt.
 *   - SVPrompts.list(): returns shallow copy of all prompts.
 *   - SVPrompts.defaultPrompt: base fallback text.
 */
(function(){
  'use strict';

  const defaultPrompt = [
    'You are an expert curriculum assistant. Use the supplied snapshot to give concise, actionable feedback.',
    'If the snapshot is empty or missing, say so and ask for the needed details.',
    'Keep responses brief and specific to the partial.',
  ].join(' ');

  // Prompt factory functions keyed by partial. Each receives optional snapshot
  // (shape: { key, markdown, raw }) and may tailor the prompt accordingly.
  const promptFns = {
    mission_vision: (snap) => 'Review mission and vision. Check clarity, alignment to institution, and distinctness between mission vs vision.',
    course_info: (snap) => [
      'Handle the course rationale and description based on the following scenarios:',
      '',
      'SCENARIO 1 - Existing course rationale & sufficient syllabus data:',
      'Check if the existing course rationale and description aligns with the entire syllabus (objectives, ILOs, SOs, teaching/learning strategies, assessment methods, etc.).',
      'If ALIGNED: Improve and enhance the existing description by making it more comprehensive, adding more relevant details, and strengthening its connection to the syllabus elements.',
      'If NOT ALIGNED: Rephrase and refocus the description to better align with the syllabus content and learning outcomes.',
      '',
      'SCENARIO 2 - Existing course rationale & insufficient syllabus data:',
      'If there is existing course rationale but the syllabus lacks sufficient detail to properly align it, simply rephrase and polish the existing description.',
      '',
      'SCENARIO 3 - No existing course rationale & sufficient syllabus data:',
      'Generate a new comprehensive, one-paragraph course rationale and description that aligns with the entire syllabus.',
      '',
      'GENERAL GUIDELINES:',
      'Structure the rationale to include: (1) What the course provides/offers to students and its relevance, (2) Key concepts, topics, or trends covered, (3) Learning methods and practical opportunities for students.',
      'Use a professional yet accessible tone suitable for a syllabus.',
      'Example format: "This course provides students with an overview of [key topic/trend] that drives [relevance]. The course will provide understanding on [main concepts] that can help [student benefit/organizational value]. This will also introduce [tools/methods] used in [field] to provide students with opportunities to apply these techniques in [practical settings]."',
      'Start your response with natural conversation (e.g., "Here\'s an improved/rephrased course description..." or similar), then provide the one-paragraph description.',
      'Ensure it is clear, detailed, cohesive with the syllabus, and directly applicable for inclusion.'
    ].join(' '),
    criteria_assessment: (snap) => [
      'Review the assessment criteria structure. Categories represent course components (e.g., lecture, lab, practical), and Assessments are evaluation methods (e.g., exams, exercises, projects) mapped to each category with percentages.',
      'Check that: (1) Assessment percentages within each category sum to 100%, (2) Overall category percentages sum to 100%, (3) The distribution reflects the course structure and workload.',
      'Suggest diverse assessment methods appropriate to each course component and aligned with the course learning outcomes.',
      'Ensure the weighting reflects the course design and academic requirements, balancing theory and practical work.',
      'Flag if percentages are missing, unbalanced, or if assessment methods need diversification.'
    ].join(' '),
    course_policies: (snap) => 'Summarize or improve policies (attendance, exams, dishonesty, dropping). Ensure tone is clear and student-facing.',
    tlas: (snap) => [
      'Generate comprehensive teaching, learning, and assessment strategies based on the entire syllabus.',
      '',
      'IMPORTANT DISTINCTION:',
      'This is the OVERALL STRATEGIC APPROACH (TLAS) describing how the course will be taught and assessed.',
      'This is NOT the weekly TLA Activities table. Do not confuse this with the detailed week-by-week schedule.',
      'Focus on describing the general teaching methods, assessment philosophy, and learning modalities used throughout the course.',
      '',
      'STRUCTURE YOUR RESPONSE:',
      '1. Start with a brief, natural conversational reply (1-2 sentences) acknowledging the request.',
      '2. Then provide the TLAS content in PARAGRAPH FORM (not bullet points).',
      '',
      'TLAS CONTENT SHOULD BE WRITTEN AS CONTINUOUS PARAGRAPHS:',
      'Paragraph 1 - Assessment Methods and Rubrics: Write flowing text describing the types of assessments used (e.g., written exams, oral exams, quizzes, assignments, presentations, case analyses, reflective journals, rubrics, portfolios, laboratory outputs). Explain how these assessments evaluate student learning and the role of rubrics in ensuring fairness.',
      '',
      'Paragraph 2 - Teaching and Learning Modalities: Write as a narrative describing the instructional approaches and modalities used throughout the course (e.g., hybrid learning, face-to-face and online sessions, video presentations, tutorials, laboratory activities, self-directed learning, web-based research, individual and group work, student-centered activities). Explain how these methods support diverse learning styles.',
      '',
      'Paragraph 3 - Assessment Instruments and Tools: Write in paragraph form specifying the evaluation methods and tools (e.g., quizzes, midterm exam, final exam, chapter tests, attendance tracking, rubric-based evaluations, oral/paper presentations, project evaluations, laboratory outputs). Describe how these instruments collectively measure course outcomes.',
      '',
      'EXAMPLE PARAGRAPH FORMAT:',
      '"Assessment Methods: Students will be evaluated using a combination of formative and summative assessments, including quizzes, written examinations, laboratory exercises, group projects, presentations, case analyses, and reflective journals. Rubrics will be used to ensure fairness and clarity in grading, especially for projects and presentations. This multifaceted approach ensures comprehensive evaluation of student learning across different domains.',
      '',
      'Teaching and Learning Methods: The course is taught using a structured program of hybrid learning (face-to-face and online), incorporating video presentations, tutorials, laboratory activities, and student-centered learning specifically through (a) self-directed learning using online materials and lectures, (b) laboratory sessions to gain practical experience and reinforce theory, (c) individual assignment work as part of laboratory activities, (d) web-based research, and (e) group-based problem solving and reporting. These diverse modalities accommodate different learning preferences and promote engagement.',
      '',
      'Assessment Tools and Instruments: Students will be assessed using a combination of rubrics, paper and pencil tests, oral and paper presentations, and portfolio methods. Specific instruments include Midterm and Final Exams, Quizzes/Chapter Tests, Attendance and Assignments, Evaluation of Laboratory Outputs using rubrics, and Projects. This comprehensive assessment battery ensures that learning outcomes are measured across cognitive, practical, and collaborative dimensions."',
      '',
      'IMPORTANT:',
      'Write as flowing, professional paragraphs - NOT as lists or bullet points.',
      'Ensure the strategies align with the course outcomes (ILOs and SOs) provided in the syllabus.',
      'Make it specific to this course\'s content, structure, and context.',
      'Use professional, clear language suitable for a syllabus.',
      'Keep the content practical and implementable.'
    ].join(' '),
    tla_activities: (snap) => [
      'Generate Teaching, Learning, and Assessment (TLA) Activities as a structured markdown table based on the syllabus snapshot.',
      '',
      'CRITICAL REQUIREMENT - TEXTBOOKS MUST BE PRESENT:',
      '- MAIN TOPICS MUST ALWAYS BE BASED ON UPLOADED TEXTBOOKS.',
      '- CHECK TEXTBOOK ALIGNMENT: Confirm uploaded textbooks/readings match the course description, ILOs, and assessment methods. If misaligned or irrelevant, DO NOT GENERATE the table; instead reply: "I cannot generate TLA Activities because the uploaded textbooks/readings are not aligned to the course. Please upload appropriate textbooks or a relevant reading list."',
      '- If the snapshot does NOT contain any textbooks, readings, or references, DO NOT generate the table.',
      '- Instead, respond with: "I cannot generate TLA Activities because no textbooks or readings have been uploaded to the syllabus. Please upload textbooks or provide a reading list first, and I will derive the main topics from those chapters/sections."',
      '- Only proceed to generate the table if textbooks/readings are present AND aligned to the course.',
      '',
      'CRITICAL REQUIREMENT - ILOs AND SOs MUST BE PRESENT:',
      '- If the snapshot lacks ILOs or SOs, DO NOT generate the TLA table.',
      '- Instead, respond with: "I cannot generate TLA Activities because the ILOs and/or SOs are missing. Please provide the ILOs and SOs first."',
      '- Only proceed when both ILOs and SOs are available in the snapshot.',
      '',
      'WHAT THIS IS (AND IS NOT):',
      '- This is the WEEKLY TLA ACTIVITIES table (18 weeks).',
      '- This is NOT the high-level TLAS narrative.',
      '',
      'OUTPUT RULES:',
      '1) Start with one short intro sentence (e.g., "Here are the TLA activities for your course:").',
      '2) Immediately output the markdown table. No extra commentary.',
      '3) Table columns must be exactly: | Ch. | Topics / Reading List | Wks. | Topic Outcomes | ILO | SO | Delivery Method |',
      '4) Use the separator row: | --- | --- | --- | --- | --- | --- | --- |',
      '',
      'WEEK CONSTRAINTS (TITLE CASE ONLY FOR EXAMS):',
      '- 18 rows total, covering Weeks 1–18.',
      '- Week 1: Orientation & Introduction; Ch., ILO, SO blank.',
      '- Week 9 (Midterm Examination): Topics/Reading List = "Midterm Examination", Wks. = "9"; ALL other cells blank including Delivery Method.',
      '- Week 17 (Final Examination): Topics/Reading List = "Final Examination", Wks. = "17"; ALL other cells blank including Delivery Method.',
      '- Week 18: Topics/Reading List = "Uploading and Submission of Grades", Wks. = "18"; ALL other cells blank.',
      '- Populate Weeks 2–8 and 10–16 with instructional topics/activities.',
      '',
      'COLUMN NOTES:',
      '- Ch.: Chapter number (sequential, e.g., 1, 2, 3); leave blank for Orientation/Exams/Week 18.',
      '- Topics / Reading List: Main topic derived from the chapter + aligned assessment tasks listed below (multi-line allowed).',
      '- Wks.: Week range assigned to that chapter (e.g., "2", "2-3", "3-4"). Duration depends on the scope and depth of the Topics/Reading List content for that chapter. Chapters typically span 2–3 weeks or run for 3 weeks straight based on content volume.',
      '- Topic Outcomes: Specific, measurable outcome (action verbs).',
      '- ILO: Comma-separated ILO numbers (blank for Orientation/Exams/Week 18).',
      '- SO: Comma-separated SO numbers (blank for Orientation/Exams/Week 18).',
      '- Delivery Method: e.g., Lecture, Lab, Discussion, Case Study, Group Work, Presentation, Written Exam, Practical Work, Online Module.',
      '',
      'CHAPTER AND TOPIC DERIVATION (FROM UPLOADED TEXTBOOKS):',
      '- Each row represents ONE CHAPTER from the textbook.',
      '- Extract Main Topics DIRECTLY from the chapters/sections/titles in the uploaded textbooks.',
      '- Use chapter numbers and titles as the basis for Main Topic naming.',
      '- Ensure Main Topics align with the sequence and structure of the textbooks.',
      '- Example: If a textbook has "Chapter 1: Introduction to Analytics", use "Main Topic 1: Introduction to Analytics" in that row.',
      '- Do not fabricate or invent topics; rely entirely on the textbook structure.',
      '- WEEK ASSIGNMENT PER CHAPTER: Assign a week range (Wks. column) based on how extensive the chapter content is. Chapters can span 2 weeks, 3 weeks, or run consecutively depending on the Topics/Reading List volume for that chapter.',
      '',
      'TASK INTEGRATION:',
      '- Prefix each instructional entry with "Main Topic X: <Title>".',
      '- In the Topics cell, put the Main Topic on the first line, add a BLANK LINE, then list aligned assessment tasks underneath with no dash prefix.',
      '- Use # for numbered tasks (Quiz #1, Assignment #2, Laboratory Activity #1). Non-numbered tasks stay plain text.',
      '- TASK SOURCE: Use ALL tasks from the Assessment Method & Distribution (AMD) partial and ONLY those tasks; do not invent or drop tasks.',
      '- TASK SPLITTING: If a task name in AMD contains a forward slash (e.g., "Assignment/Research Review"), treat it as TWO SEPARATE tasks. Split them and assign each a number (e.g., "Assignment #2" and "Research Review #1"). Place these tasks in DIFFERENT rows under different Main Topics based on your judgment for optimal course flow. Never combine slash-separated tasks in the same row.',
      '- TASK DISTRIBUTION RULES (CRITICAL):',
      '  * ALL tasks from AMD should be DISTRIBUTED across multiple rows throughout the semester',
      '  * EXCEPTION: Midterm Project and Final Examination should only be conducted ONCE (not distributed)',
      '  * LABORATORY EXAM RULE: Laboratory Exams should be conducted ONLY TWICE - one in Week 8 (1 week before Midterm) and one in Week 16 (1 week before Finals)',
      '  * Distribute recurring tasks (quizzes, assignments, activities, lab exercises) evenly throughout Weeks 2-16',
      '  * Example: If AMD shows "Quizzes (3 instances)", distribute as Quiz #1, Quiz #2, Quiz #3 across different topic rows',
      '  * Example: If AMD shows "Assignments (4 instances)", distribute as Assignment #1, Assignment #2, Assignment #3, Assignment #4 across different topic rows',
      '  * Midterm Project appears ONLY once, typically around Week 7-8',
      '  * Final Examination appears ONLY in Week 17 (already fixed in Week 17 row)',
      '- PLACE TASKS: Use the AMD tasks snapshot to place each task under the closest matching Main Topic; keep pacing realistic. Use AI judgment to distribute tasks for best course flow and learning progression.',
      '- ALIGNMENT RULES (CRITICAL - FOLLOW THESE RULES):',
      '  * The Topics/Reading List column contains TWO types of content: TOPICS (from textbooks) and TASKS (from AMD)',
      '  * TASK ALIGNMENT TO ILO: For tasks listed in a row, find the task in AMD and check which ILO columns have values (and which CPA columns have values). The task aligns to those ILOs where the AMD table shows values. Use ONLY the AMD mappings for task-to-ILO alignment.',
      '  * TASK ALIGNMENT TO SO: For tasks, AI decides which SO(s) best fit based on the task type and purpose.',
      '  * TOPIC ALIGNMENT TO ILO: For topics (Main Topic lines), AI decides which ILO(s) best fit the topic based on content and outcomes.',
      '  * TOPIC ALIGNMENT TO SO: For topics (Main Topic lines), AI decides which SO(s) best fit the topic based on content and outcomes.',
      '- COMBINED ILO/SO COLUMNS: When a row contains BOTH a topic AND tasks:',
      '  * Collect ILO values from the topic (AI decides)',
      '  * Collect ILO values from each task in that row (from AMD - check which ILO columns have values for that task)',
      '  * Combine both sets and deduplicate to create the final ILO column value (e.g., topic has ILO1,2 + task has ILO2,3 → row shows "1,2,3")',
      '  * Collect SO values from the topic (AI decides)',
      '  * Collect SO values from each task in that row (AI decides)',
      '  * Combine both sets and deduplicate to create the final SO column value',
      '- KEY RULE: A task in AMD is aligned to an ILO if that task has a value in that ILO column AND in the CPA columns in the AMD table.',
      '- Choose week numbers/ranges that reflect workload when multiple tasks sit under a topic.',
      '- If a project presentation/submission exists, include it in Week 17 with the Final Examination cell content.',
      '',
      'DISTRIBUTION & COVERAGE:',
      '- Distribute quizzes/assessments every 2–3 topics; cover all ILOs/SOs across Weeks 2–16.',
      '- Keep logical progression and realistic pacing aligned to the textbook chapter sequence.',
      '',
      'FORMATTING ENFORCEMENT:',
      '- Use proper markdown table pipes; no extra text after the table.',
      '- Orientation/Exam/Grades rows: only Wks. cell populated (except Orientation has topic/outcomes/delivery).',
      '',
      'EXAMPLE OUTPUT:',
      'Here are the TLA activities for your course:',
      '',
      '| Ch. | Topics / Reading List | Wks. | Topic Outcomes | ILO | SO | Delivery Method |',
      '| --- | --- | --- | --- | --- | --- | --- |',
      '|  | Orientation & Introduction | 1 | VMGO Orientation, Presentation of Syllabus, Class Rules |  |  | Face-to-face Discussion |',
      '| 1 | Main Topic 1: Overview of Big Data and Analytics | 2-3 | Explain fundamental concepts of data analytics | 1,2 | 1 | Lecture, Videos |',
      '| 2 | Main Topic 2: Statistical Foundations | 4-5 | Apply statistical methods to analyze datasets | 2,3 | 1,2 | Lecture, Lab Work |',
      '|  | Midterm Examination | 9 |  |  |  |  |',
      '|  | Final Examination | 17 |  |  |  |  |',
      '|  |  | 18 |  |  |  |  |'
    ].join(' '),
    assessment_tasks: (snap) => [
      'Review the Assessment Method and Distribution Map. Output ONLY a markdown table (no cards, no extra paragraphs).',
      '',
      'TABLE COLUMN DEFINITIONS:',
      '- Code: Task code (e.g., ME, FE, PRJ)',
      '- Task: Task name (e.g., "Midterm Exam", "Project")',
      '- I/R/D: Type of task (I=Introduction, R=Reinforce, D=Deliverable)',
      '- %: Percentage weight of task in overall grade',
      '- ILO#: Distribution of items/points to each ILO (numbers add up to CPA totals)',
      '- C: Cognitive domain (total items/points for cognitive assessment)',
      '- P: Psychomotor domain (total items/points for psychomotor skills)',
      '- A: Affective domain (total items/points for attitude/appreciation)',
      '',
      'EXAMPLE ROW LOGIC:',
      'Midterm Exam (I type): C=75 means 75 cognitive items → distributed as ILO1=35, ILO2=35 (adds to 75)',
      'Project (D type): P=1000 means 1000 points for deliverable → distributed as ILO2=1000 (deliverable assigned only to ILO2)',
      'Values in ILO columns must sum to their corresponding CPA column (C+P+A totals across ILO columns equals the CPA total for that task).',
      '',
      'INSTRUCTIONS:',
      'If the snapshot is empty or missing tasks, ask the user for assessment task details: code, name, I/R/D type, weight %, and C/P/A totals with ILO distribution.',
      'Or propose a concise starter table (e.g., Midterm, Final, 1-2 assignments/projects) that the user can edit.',
      'Use exact ILO columns from snapshot (ILO1..ILOn); preserve existing codes and structure.',
      'Ensure weights (%) sum to 100%; keep distributions realistic and balanced.',
      'CATEGORY PROMPTING:',
      'When tasks include category labels (Laboratory, Lecture, Major Requirements, Minor Requirements, Additional Requirements), treat each as a category row and list their specific assessments directly below them in the table.',
      'Keep category rows as the parent task name; list the category-specific assessments as the tasks underneath with their own codes, I/R/D types, weights, and CPA/ILO distributions.'
    ].join(' '),
    assessment_schedule: (snap) => [
      'Generate an Assessment Schedule mapping that marks which assessment tasks occur in which weeks.',
      '',
      'INPUT: You will receive snapshots containing:',
      '1. TLA Activities table with tasks and their assigned weeks (may include ranges like "2-3", "12-14", etc.)',
      '2. Assessment Method & Distribution (AMD) with all assessment tasks',
      '3. Current Assessment Schedule structure if it exists',
      '',
      'TASK:',
      'Map each assessment task from the Assessment Method & Distribution to the weeks it appears in the TLA Activities table.',
      'For each task, identify all weeks where it is scheduled, and mark those weeks with "x".',
      '',
      'OUTPUT REQUIREMENTS:',
      'You MUST output ONLY valid JSON in a ```json``` fenced code block. No other text before or after.',
      '',
      'JSON STRUCTURE:',
      '{',
      '  "weeks": ["1", "2-3", "4-5", "6", "7-8", "9", "10-11", "12-14", "15", "16", "17"],',
      '  "mappings": [',
      '    { "name": "Midterm Exam", "week_marks": { "1": "", "2-3": "", ..., "9": "x", ..., "17": "" }, "position": 0 },',
      '    { "name": "Quizzes/Chapter Tests", "week_marks": { "1": "", "2-3": "x", ..., "17": "" }, "position": 1 },',
      '    ...',
      '  ]',
      '}',
      '',
      'FIELD DESCRIPTIONS:',
      '- weeks: Array of all week columns EXACTLY AS THEY APPEAR IN THE TLA TABLE (weeks 1-17 ONLY, excluding week 18 which is for grade submission). Include ranges (e.g., "2-3", "12-14") without separating them.',
      '- mappings: Array of assessment tasks, each containing:',
      '  * name: The assessment task name (string, from Assessment Method & Distribution)',
      '  * week_marks: Object mapping each week string (from the weeks array) to "x" (mark present) or "" (empty string, not present)',
      '  * position: Integer representing the order/position of this task (0-indexed)',
      '',
      'CRITICAL RULE - PRESERVE WEEK RANGES:',
      '- Extract the exact week values from the TLA Activities "Wks." column',
      '- Do NOT expand or separate ranges (e.g., "2-3" stays as "2-3", NOT ["2", "3"])',
      '- Do NOT combine separate weeks into ranges',
      '- Preserve the EXACT format and order from the TLA table',
      '- EXCLUDE week 18 (uploading/submission week) - only include weeks 1-17',
      '',
      'MARKING RULES:',
      '- For each task in Assessment Method & Distribution:',
      '  1. Find the task in the TLA Activities table',
      '  2. Identify the "Wks." column value for that task',
      '  3. If the week is 18, DO NOT include it (skip this task or exclude week 18 from it)',
      '  4. Find the matching week entry in your weeks array (same exact text)',
      '  5. Mark that week entry with "x" in week_marks',
      '  6. All other week entries get empty string ""',
      '- If a task is not found in TLA Activities or only exists in week 18, mark all weeks as "" (empty)',
      '',
      'WEEK EXAMPLES FROM TLA:',
      '- If TLA Wks. column shows "2-3": Find "2-3" in weeks array and mark it with "x"',
      '- If TLA Wks. column shows "12-14": Find "12-14" in weeks array and mark it with "x"',
      '- If TLA Wks. column shows "5": Find "5" in weeks array and mark it with "x"',
      '- If TLA Wks. column shows "9": Find "9" in weeks array and mark it with "x"',
      '- If TLA Wks. column shows "18": SKIP this entry (do not include week 18)',
      '',
      'IMPORTANT:',
      '- Output ONLY the JSON block; no explanation, commentary, or preamble',
      '- The weeks array MUST include only weeks 1-17 (NEVER include week 18)',
      '- Weeks array should match the exact week values from the TLA Activities "Wks." column, excluding week 18',
      '- Preserve ALL ranges exactly as they appear (do not expand "2-3" to separate entries)',
      '- Preserve ALL single weeks as strings',
      '- Do not include any text outside the json code block',
      '- Follow the exact structure above'
    ].join(' '),
    ilo: (snap) => [
      'Generate a comprehensive list of Intended Learning Outcomes (ILOs) for this course based on the entire syllabus.',
      '',
      'STRUCTURE YOUR RESPONSE:',
      '1. Start with a brief, natural conversational reply (1-2 sentences) acknowledging the request.',
      '2. Then provide the ILOs in TABLE FORMAT (this will appear in a card and be inserted into the syllabus).',
      '',
      'TABLE FORMAT REQUIREMENTS:',
      'Create a markdown table with TWO columns:',
      '| ILO # | Intended Learning Outcome |',
      '| --- | --- |',
      '| ILO 1 | [Specific, measurable outcome statement] |',
      '| ILO 2 | [Specific, measurable outcome statement] |',
      '...',
      '',
      'ILO CONTENT GUIDELINES:',
      'Each ILO should be:',
      '- Specific and measurable (use action verbs like: understand, apply, analyze, create, evaluate, synthesize, etc.)',
      '- Aligned with the course topics, assessments, and learning activities provided in the syllabus',
      '- Written at an appropriate level for the course (e.g., introductory, intermediate, advanced)',
      '- Focused on what students will be able to DO or KNOW after completing the course',
      '- Clear, concise, and free of jargon',
      '',
      'EXAMPLE TABLE:',
      '| ILO # | Intended Learning Outcome |',
      '| --- | --- |',
      '| ILO 1 | Understand fundamental concepts and principles of business analytics and their application in organizational decision-making |',
      '| ILO 2 | Apply data analysis techniques using relevant tools and software to extract insights from real-world business data |',
      '| ILO 3 | Analyze business problems and develop data-driven solutions using analytical methodologies |',
      '| ILO 4 | Create visualizations and reports that effectively communicate analytical findings to diverse stakeholders |',
      '| ILO 5 | Evaluate the effectiveness of analytical solutions and recommend improvements based on business impact |',
      '',
      'IMPORTANT:',
      'Generate 4-8 ILOs depending on course depth and complexity.',
      'Ensure ILOs cover cognitive levels from basic understanding to higher-order thinking.',
      'Align ILOs with the course learning activities, assessments, and outcomes provided in the syllabus.',
      'Use consistent, professional language throughout.',
      'Do NOT include explanatory text after the table - only the table itself.'
    ].join(' '),
    so: (snap) => 'Check SO list for completeness and distinctness. Ensure phrasing is outcome-based and aligned to accreditation.',
    cdio: (snap) => 'Review CDIO skills coverage. Suggest integration points in activities and assessments.',
    sdg: (snap) => 'Check SDG alignment. Suggest authentic integration of relevant goals in topics/assessments.',
    iga: (snap) => 'Review institutional graduate attributes and how they appear in the syllabus. Suggest tighter linkage to activities/assessments.',
    ilo_so_cpa_mapping: (snap) => [
      'Generate an ILO-SO-CPA mapping that shows task codes for each ILO-SO combination and CPA domain.',
      '',
      'CRITICAL VALIDATION - CHECK BEFORE GENERATING:',
      '- If there are NO ILOs with any alignment to tasks, DO NOT generate the mapping.',
      '- If there are NO SOs with any alignment to tasks, DO NOT generate the mapping.',
      '- If ILOs or SOs exist but have NO task alignments, respond with: "Cannot generate ILO-SO-CPA mapping because there are no task alignments in the TLA Activities table. Please ensure tasks are properly aligned to ILOs and SOs in the TLA Activities section first."',
      '- Only proceed if there are actual task-to-ILO and task-to-SO alignments in the TLA Activities table.',
      '',
      'EXISTING MAPPINGS HANDLING:',
      '- If the snapshot contains existing ILO-SO-CPA mappings, IGNORE them completely.',
      '- Always REGENERATE the mappings from scratch based on the current TLA Activities and AMD data.',
      '- Do NOT preserve or reference any existing mapping values.',
      '- The generated mappings will REPLACE any existing mappings in the database.',
      '',
      'INPUT: You will receive snapshots containing:',
      '1. ILOs (Intended Learning Outcomes) from the syllabus',
      '2. SOs (Student Outcomes) institutional codes',
      '3. TLA Activities table showing task codes aligned to ILOs and SOs',
      '4. Assessment Method & Distribution (AMD) with task codes and CPA classifications',
      '',
      'TASK MAPPING PROCESS (Follow these steps in order):',
      'Step 1: Scan the TLA Activities "Topics/Reading List" column for all task names (e.g., "Midterm Exam", "Final Exam", "Quiz #1").',
      'Step 2: For each task found, look up that task in the AMD table to get:',
      '  - Its task code (e.g., ME, FE, QCT)',
      '  - Which ILO columns have values in AMD (source of truth for task→ILO alignment)',
      'Step 3: Go back to the TLA Activities table and check which ILO columns that task row aligns with in TLA.',
      'Step 4: Also check which SO columns that task row aligns with in TLA Activities.',
      'Step 5: Use the task code from AMD and create mappings based on BOTH AMD ILO columns AND TLA Activities ILO/SO columns.',
      '',
      'TASK OUTPUT:',
      'For each ILO, create a row with:',
      '- SO columns: comma-separated task codes for each ILO-SO pair (based on TLA Activities SO alignment)',
      '- C column: comma-separated task codes with Cognitive domain (from AMD)',
      '- P column: comma-separated task codes with Psychomotor domain (from AMD)',
      '- A column: comma-separated task codes with Affective domain (from AMD)',
      '',
      'OUTPUT REQUIREMENTS:',
      'You MUST output ONLY valid JSON in a ```json``` fenced code block. No other text before or after.',
      '',
      'JSON STRUCTURE:',
      '{',
      '  "so_columns": ["SO1", "SO2", "SO3"],',
      '  "mappings": [',
      '    {',
      '      "ilo_text": "ILO1",',
      '      "sos": {"SO1": "FE,ME", "SO2": "ME", "SO3": "FE,ME"},',
      '      "c": "FE,ME",',
      '      "p": null,',
      '      "a": null,',
      '      "position": 0',
      '    },',
      '    {',
      '      "ilo_text": "ILO2",',
      '      "sos": {"SO1": "ME", "SO2": "FE,ME", "SO3": null},',
      '      "c": "FE,ME",',
      '      "p": null,',
      '      "a": null,',
      '      "position": 1',
      '    }',
      '  ]',
      '}',
      '',
      'FIELD DESCRIPTIONS:',
      '- so_columns: Array of all SO codes found in the mappings (e.g., ["SO1", "SO2", "SO3"])',
      '- mappings: Array of ILO mapping rows:',
      '  * ilo_text: The ILO label as string (e.g., "ILO1", "ILO2")',
      '  * sos: JSON object where keys are SO labels and values are comma-separated task codes or null',
      '  * c: Comma-separated task codes for Cognitive domain or null if none',
      '  * p: Comma-separated task codes for Psychomotor domain or null if none',
      '  * a: Comma-separated task codes for Affective domain or null if none',
      '  * position: Integer representing ILO row order (0-indexed)',
      '',
      'MAPPING RULES:',
      '- STEP-BY-STEP PROCESS:',
      '  1. Find all tasks in TLA Activities "Topics/Reading List" column',
      '  2. For each task, look it up in AMD to get task code and check which AMD ILO columns have values',
      '  3. Return to TLA Activities to check which ILO and SO columns that task aligns with',
      '  4. Use task code from AMD for all mappings',
      '- Collect ALL unique SO codes found in the TLA Activities table → add to so_columns array, sorted by number (SO1, SO2, SO3, etc.)',
      '- CRITICAL: Only include SO codes in so_columns if they have at least one task alignment with any ILO. Do NOT include SO columns that have no alignments at all.',
      '- For each ILO in the syllabus:',
      '  1. BEFORE creating a mapping entry: Check if this ILO has ANY task alignments. If an ILO has NO alignments at all, SKIP it and do not create a row for it.',
      '  2. Only create a mapping entry for ILOs that have at least one task alignment',
      '  3. In sos object, for each SO in so_columns: list task codes (from AMD) for tasks that align to BOTH this ILO (in TLA) AND that SO (in TLA)',
      '  4. In c field: list all task codes (from AMD) for this ILO that have Cognitive domain values in AMD',
      '  5. In p field: list all task codes (from AMD) for this ILO that have Psychomotor domain values in AMD',
      '  6. In a field: list all task codes (from AMD) for this ILO that have Affective domain values in AMD',
      '- Separate multiple task codes with "," (comma NO space)',
      '- Use null (not empty string) for empty cells',
      '- Task codes come from TLA or AMD (e.g., "ME", "FE", "QCT", "ARR", "PR", "LE", "LEX")',
      '- DO NOT generate rows for ILOs with no alignments',
      '- DO NOT generate SO columns with no alignments across all ILOs',
      '',
      'EXAMPLE OUTPUT:',
      '{',
      '  "so_columns": ["SO1", "SO2", "SO3"],',
      '  "mappings": [',
      '    {',
      '      "ilo_text": "ILO1",',
      '      "sos": {"SO1": "FE,ME", "SO2": "ME", "SO3": "FE,ME"},',
      '      "c": "FE,ME",',
      '      "p": null,',
      '      "a": null,',
      '      "position": 0',
      '    },',
      '    {',
      '      "ilo_text": "ILO2",',
      '      "sos": {"SO1": "ME", "SO2": "FE,ME", "SO3": null},',
      '      "c": "FE,ME",',
      '      "p": null,',
      '      "a": null,',
      '      "position": 1',
      '    },',
      '    {',
      '      "ilo_text": "ILO3",',
      '      "sos": {"SO1": "FE", "SO2": "ME", "SO3": "FE"},',
      '      "c": "FE,ME",',
      '      "p": null,',
      '      "a": null,',
      '      "position": 2',
      '    }',
      '  ]',
      '}',
      '',
      'IMPORTANT:',
      '- Output ONLY the JSON block; no explanation, commentary, or preamble',
      '- so_columns should list ALL unique SO codes found in the data, sorted numerically',
      '- ilo_text should be the ILO label only (e.g., "ILO1", not full ILO description)',
      '- sos keys must match the SO codes in so_columns array',
      '- Task codes should be comma-separated WITHOUT spaces (e.g., "FE,ME" not "FE, ME")',
      '- Use null (not "" or "-") for empty cells in sos, c, p, a fields',
      '- Position values must be sequential starting from 0 matching the ILO order',
      '- Do not include any text outside the json code block',
      '- Follow the exact structure above'
    ].join(' '),
    ilo_iga_mapping: (snap) => [
      'Generate Task-to-IGA mapping showing which tasks (from AMD) align to which Institutional Graduate Attributes (IGAs), with ILO grouping.',
      '',
      'CRITICAL VALIDATION - CHECK BEFORE GENERATING:',
      '- If there are NO tasks in AMD with ILO alignments, output: {"error": "No task-to-ILO alignments found. Please ensure tasks are properly mapped to ILOs first."}',
      '- If there are NO IGAs defined, output: {"error": "No IGAs defined. Please define IGAs first."}',
      '- After processing: If there are NO ILO rows with any task alignments, DO NOT generate the mapping. Output: {"error": "No ILO rows have task alignments after filtering."}',
      '- After processing: If there are NO IGA columns with any task mappings, DO NOT generate the mapping. Output: {"error": "No IGA columns have task mappings after filtering."}',
      '- If both conditions occur (no ILO rows AND no IGA columns with alignments), output: {"error": "No alignments found. Cannot generate ILO-IGA mapping."}',
      '- Only proceed with full JSON mapping if at least one ILO row has task alignments AND at least one IGA column has task mappings.',
      '',
      'EXISTING MAPPINGS HANDLING:',
      '- If the snapshot contains existing ILO-IGA mappings, IGNORE them completely.',
      '- Always REGENERATE the mappings from scratch based on the current AMD and IGA data.',
      '- Do NOT preserve or reference any existing mapping values.',
      '- The generated mappings will REPLACE any existing mappings in the database.',
      '',
      'INPUT: You will receive snapshots containing:',
      '1. ILOs (Intended Learning Outcomes) from the syllabus',
      '2. IGAs (Institutional Graduate Attributes) from the institution',
      '3. AMD (Assessment Method & Distribution) table with all tasks EXCEPT the category column',
      '',
      'TASK MAPPING PROCESS (Follow these steps in order):',
      'Step 1: Scan the AMD table for all tasks (EXCEPT category rows) and their task codes.',
      'Step 2: For each task, check the ILO columns in AMD - if a column has a value, that task is aligned to that ILO.',
      'Step 3: Read all IGA codes and descriptions from the IGA snapshot.',
      'Step 4: For each task-ILO alignment, analyze the IGA descriptions and assign the task code to the MOST APPROPRIATE IGA (can be any IGA1, IGA2, IGA3, IGA4, etc. - not just IGA1).',
      'Step 5: Build the mapping where each ILO row contains task codes grouped by their assigned IGA columns.',
      '',
      'TASK OUTPUT:',
      'For each ILO that has task alignments in AMD:',
      '1. Group task codes by the IGA they map to (distribute across different IGAs based on best fit)',
      '2. Each task code appears under exactly one IGA column for that ILO row',
      '3. Different tasks can map to different IGAs (do NOT map everything to IGA1)',
      '',
      'OUTPUT REQUIREMENTS:',
      'You MUST output ONLY valid JSON in a ```json``` fenced code block. No other text before or after.',
      '- If no ILO rows or IGA columns remain after filtering, output an empty JSON: { "iga_columns": [], "mappings": [] }',
      '',
      'JSON STRUCTURE:',
      '{',
      '  "iga_columns": ["IGA1", "IGA2", "IGA3"],',
      '  "mappings": [',
      '    {',
      '      "ilo_text": "ILO1",',
      '      "igas": {"IGA1": "ME,FE", "IGA2": null, "IGA3": "QCT"},',
      '      "position": 0',
      '    },',
      '    {',
      '      "ilo_text": "ILO2",',
      '      "igas": {"IGA1": null, "IGA2": "ARR", "IGA3": "LEC"},',
      '      "position": 1',
      '    }',
      '  ]',
      '}',
      '',
      'FIELD DESCRIPTIONS:',
      '- iga_columns: Array of all IGA codes/labels that have at least one task mapped to them (e.g., ["IGA1", "IGA2", "IGA3"])',
      '- mappings: Array of ILO mapping rows:',
      '  * ilo_text: The ILO label as string (e.g., "ILO1", "ILO2")',
      '  * igas: JSON object where keys are IGA labels and values are:',
      '    - Comma-separated task codes (no spaces) if tasks align to that IGA for this ILO (e.g., "ME,FE")',
      '    - null if no tasks align to that IGA for this ILO',
      '  * position: Integer representing ILO row order (0-indexed)',
      '',
      'MAPPING RULES:',
      '- STEP-BY-STEP PROCESS:',
      '  1. Scan AMD for all tasks (except category) and their codes',
      '  2. For each task, check AMD ILO columns - if a column has a value, that task aligns to that ILO',
      '  3. Read all IGAs and their descriptions',
      '  4. For each task-ILO pair, assign the task code to exactly ONE IGA based on IGA descriptions',
      '  5. Group task codes by IGA for each ILO row',
      '- Source of truth: Use ONLY the AMD table for task-to-ILO alignments (column headers in AMD show which ILOs tasks map to). If AMD shows a task aligned to ILO1 only, keep it ONLY under ILO1 (e.g., ARR in the sample aligns only to ILO1).',
      '- Exclude the AMD category column - map ALL OTHER tasks',
      '- Collect all IGA codes from snapshots → add to iga_columns array',
      '- CRITICAL: Only include IGA codes in iga_columns if they have at least one task mapped to them.',
      '- For each ILO that has at least one task in AMD:',
      '  1. Collect ALL tasks from AMD that have this ILO code in their ILO alignment column(s)',
      '     - If AMD ILO column has a value for a task, that task is aligned to that ILO',
      '     - If AMD ILO column is blank/empty for a task, that task is NOT aligned to that ILO',
      '     - If a task has multiple ILO alignments in AMD, add that task to each aligned ILO row',
      '  2. For each collected task, assign it to EXACTLY ONE IGA (not multiple IGAs, not zero)',
      '  3. Select the IGA that best matches based on analyzing ALL IGA descriptions - tasks should be distributed across different IGAs based on their nature and the IGA descriptions',
      '  4. DO NOT default all tasks to IGA1 - intelligently assign each task to the most appropriate IGA (IGA1, IGA2, IGA3, IGA4, etc.)',
      '  5. Group task codes by their assigned IGA in the igas object (comma-separated, no spaces)',
      '- For each IGA column: if an ILO has no tasks assigned to that IGA, use null (not empty string)',
      '- DO NOT generate rows for ILOs with no task alignments in AMD',
      '- DO NOT generate IGA columns with no tasks assigned to them across all ILOs',
      '- If both ILO rows and IGA columns would be empty after filtering, output an empty JSON block (see Output Requirements)',
      '- Each task code can only appear in ONE IGA column per ILO row (one-to-one mapping per task)',
      '',
      'IMPORTANT:',
      '- Output ONLY the JSON block; no explanation, commentary, or preamble',
      '- Task codes come from AMD (e.g., "ME", "FE", "QCT", "ARR", "PR", "LE", "LEC")',
      '- Comma-separated task codes with NO SPACES (e.g., "ME,FE" not "ME, FE")',
      '- Use null (not "" or "-") for empty cells in the igas object',
      '- Position values must be sequential starting from 0 matching the ILO order',
      '- Do not include any text outside the json code block',
      '- Follow the exact structure above'
    ].join(' '),
    ilo_cdio_sdg_mapping: (snap) => 'Evaluate ILO to CDIO and SDG mapping. Look for gaps, misalignments, or overstuffed outcomes.',
    textbook: (snap) => 'Review textbook and references. Check recency and fit. Suggest newer editions or open resources if needed.',
    general_info: (snap) => [
      'This section appears to be empty or incomplete in the syllabus.',
      'Do not reference or display the snapshot data provided.',
      'Instead, provide helpful suggestions for what should be included, best practices, and a brief example or template to guide the faculty member.',
      'Respond based on general syllabus design best practices and educational frameworks without showing or quoting the snapshot content.',
      'Be encouraging and practical in your suggestions.'
    ].join(' '),
  };

  function isSnapshotEmpty(snapshot){
    if (!snapshot) return true;
    if (snapshot.raw === null || snapshot.raw === undefined) return true;
    const raw = snapshot.raw;
    // Check for common empty patterns
    if (Array.isArray(raw.rows) && raw.rows.length === 0) return true;
    if (Array.isArray(raw.sections) && raw.sections.length === 0) return true;
    if (Array.isArray(raw.ilos) && raw.ilos.length === 0) return true;
    if (Array.isArray(raw.sos) && raw.sos.length === 0) return true;
    if (Array.isArray(raw.igas) && raw.igas.length === 0) return true;
    if (Array.isArray(raw.cdios) && raw.cdios.length === 0) return true;
    if (Array.isArray(raw.sdgs) && raw.sdgs.length === 0) return true;
    if (!raw.vision && !raw.mission) return true; // mission_vision
    if (raw.tlas === '' || raw.tlas === '-') return true; // tlas
    return false;
  }

  function get(key, snapshot){
    // If snapshot is empty, use general info prompt instead
    if (isSnapshotEmpty(snapshot)) {
      const fn = promptFns['general_info'];
      if (typeof fn === 'function') {
        try { return fn(snapshot); } catch(_) { /* fall through */ }
      }
    }

    const fn = promptFns[key];
    if (typeof fn === 'function') {
      try { return fn(snapshot); } catch(_) { /* fall through */ }
    }
    return defaultPrompt;
  }

  function set(key, promptOrFn){
    if (!key) return;
    promptFns[key] = promptOrFn;
  }

  function list(){
    const keys = Object.keys(promptFns);
    const out = {};
    keys.forEach(k => { out[k] = '[Function]'; });
    return out;
  }

  function getAll(){
    const keys = Object.keys(promptFns);
    const out = {};
    keys.forEach(k => {
      try {
        const fn = promptFns[k];
        if (typeof fn === 'function') {
          out[k] = fn(null);
        }
      } catch(_) {
        out[k] = '';
      }
    });
    return out;
  }

  window.SVPrompts = {
    get,
    set,
    list,
    getAll,
    defaultPrompt,
  };
})();
